
project_id = "jkgqjeadviqmxwmwwkma"

[functions.ai-agent-processor]
verify_jwt = false

[functions.ai-data-chat]
verify_jwt = false

[functions.ai-summary-report]
verify_jwt = false

[functions.platform-chatbot]
verify_jwt = false
