// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkgqjeadviqmxwmwwkma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprZ3FqZWFkdmlxbXh3bXd3a21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMzAyMjQsImV4cCI6MjA2NjYwNjIyNH0.WAa8MGjgDaxA8Wx27nE-wR6pEdYTdJjb6vW_93CCgOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);